@startuml

class Coleccion {
    - titulo : String
    - descripcion : String
    - hechos : List<Hecho>
}

abstract class Hecho {
    - titulo : String
    - descripcion : String
    - categoria : // TODO
    - contenidoMultimedial : // TODO
    - lugarDelAcontecimiento : Lugar
    - fechaDelAcontecimiento : LocalDateTime
    - fechaDeCarga : LocalDateTime
    - origen : OrigenDeHecho
}

enum OrigenDeHecho {
    CARGA_MANUAL,
    DATASET,
    CONTRIBUIDOR
}

class HechoDeTexto extends Hecho {
}

class HechoConSoporteParaContenidoMultimedia extends Hecho {
}

class Lugar {
    - nombre : String
    - latitud : Integer
    - longitud : Integer
}




class Usuario {
    + publicarHecho(Hecho unHecho)) : void
    + solicitarEliminarHecho(Hecho unHecho)) : void
}

class Contribuyente extends Usuario {
    - nombre : String
    - apellido : String
    - edad : Integer

    + buscarHecho(Hecho unHecho) : void
}

class Visualizador extends Usuario {
}

class Administrador {
    + crearColeccion() : void
    + importarHechosDesdeCSV() : void
    + aceptarSolicitudDeEliminacionDeHecho(SolicitudDeEliminacionDeHecho unaSolicitud) : void
    + rechazarSolicitudDeEliminacionDeHecho(SolicitudDeEliminacionDeHecho unaSolicitud) : void
}

class SolicitudDeEliminacionDeHecho {
    - hecho : Hecho
    - justificacion : String
    - estadoDeSolicitud : EstadoSolicitudDeEliminacion
}

enum EstadoSolicitudDeEliminacion {
    PENDIENTE,
    APROBADA,
    RECHAZADA
}


Coleccion --> "*" Hecho
Hecho --> Usuario
Administrador --> SolicitudDeEliminacionDeHecho
Administrador --> Coleccion
Lugar o-l- Hecho
Hecho --* OrigenDeHecho
SolicitudDeEliminacionDeHecho --* EstadoSolicitudDeEliminacion

@enduml
