@startuml

class Vehiculo {
    - datosVehiculo : DatosVehiculo
    - poliza : Poliza
    - historialCobertura : List<HistorialDeCobertura>

    + darDeBaja() : void
}

class DatosVehiculo {
    - marca : Marca
    - modelo : Modelo
    - categoria : Categoria
    - anioDeFabricacion : Integer
    - numeroDeChasis : Integer
    - dominio : String
}

class Marca {
    - nombre : String
}

class Modelo {
    - nombre : String
}

class Categoria {
    - nombre : String
}

class Poliza {
    - vehiculo : Vehiculo
    - numero : Integer
    - fechaDeEmision : LocalDate
    - categoria : TipoDeCategoria
    - calculadorDePoliza : CalculadorDePoliza
    - estadoPoliza : EstadoDePoliza
    - zonaHabitual : ZonaHabitual

    + cotizarValorDePoliza() : Double
}

enum EstadoDePoliza {
    EMITIDA,
    PENDIENTE_REVISION
}

class HistorialDeCobertura {
    - fechaModificacion : LocalDate
    - detalle : String
}

enum TipoDeCategoria {
    AUTO_PARTICULAR,
    CAMIONETA_DE_CARGA,
    MOTOCICLETA_URBANA,
    TAXI_REMIS
}

class Cliente {
    - polizas : List<Poliza>
    - nombre : String
    - apellido : String
    - CUIT : Integer
    - condicionIVA : CondicionIVA
    - medioDeContacto : MedioDeContacto
}

class CondicionIVA {
    - nombre : String
    - descripcion : String
}

class MedioDeContacto {
    - email : String
    - telefono : Integer
    - whatsapp : Integer
}

class SolicitudDePoliza {
    - cliente : Cliente
    - nivelDeCobertura : Cobertura
    - ubicacionHabitual : Ubicacion
    - categoria : TipoDeCategoria
    - condiciones : List<ICondicion>

    + esAsegurable() : Boolean
}

class Cobertura {
    -nombre: String
    -descripcion: String
}

class Ubicacion {
    - latitud : Long
    - longitud : Long
}

class CalculadorDePoliza {
    - serviciosExternos : List<IServicioExternoDeCalculo>
    - cantidadDeSiniestros : Integer

    + calcularPoliza(Vehiculo unVehiculo) : Double
}

interface IServicioExternoDeCalculo {
    + calcularValor(Vehiculo unVehiculo) : Double
}

class AdapterServicio1 implements IServicioExternoDeCalculo {
    - servicio1API : Servicio1API

    + calcularValor(Vehiculo unVehiculo)) : Double
}

class Servicio1API {
    + ejecutarCalculo(Integer unAnio, Marca unaMarca, Modelo unModelo) : Double
}

class AdapterServicio2 implements IServicioExternoDeCalculo {
    - servicio2API : Servicio2API

    + calcularValor(Vehiculo unVehiculo)) : Double
}

class Servicio2API {
    + ejecutarCalculo(Integer indiceDeRobo, Integer accidentes, Integer desastresNaturales) : Double
}

class AdapterServicio3 implements IServicioExternoDeCalculo {
    - servicio3API : Servicio3API

    + calcularValor(Vehiculo unVehiculo)) : Double
}

class Servicio3API {
    + ejecutarCalculo(Integer costoPromedio) : Double
}

interface ICondicion {
    + cumpleCondicion() : Boolean
}

class CondicionPorAnio implements ICondicion {
    + cumpleCondicion() : Boolean
}

class CondicionPorKM implements ICondicion {
    + cumpleCondicion() : Boolean
}

class AlertaDeUbicacion {
    - fechaHora : LocalDateTime
    - ubicacionDeAlerta : Ubicacion
    - poliza : Poliza
}

class ZonaHabitual {
    - centro : Ubicacion
    - radioKm : Double
}

class ReceptorGPS {
    - vehiculo : Vehiculo

    + decodificarDatos(String ubicacion) : Ubicacion
    + existeAlerta() : Boolean
}

class GPS {
    - receptor : ReceptorGPS

    + recibirDatos(String ubicacion) : void
}

Vehiculo --> DatosVehiculo
Vehiculo --> Poliza
Vehiculo --> HistorialDeCobertura : "*"

DatosVehiculo --> Marca
DatosVehiculo --> Modelo
DatosVehiculo --> Categoria

Poliza --> Vehiculo
Poliza --> TipoDeCategoria
Poliza --> CalculadorDePoliza
Poliza --> EstadoDePoliza
Poliza --> ZonaHabitual

ZonaHabitual --> Ubicacion

CalculadorDePoliza --> IServicioExternoDeCalculo

AdapterServicio1 --> Servicio1API
AdapterServicio2 --> Servicio2API
AdapterServicio3 --> Servicio3API

Cliente --> Poliza : "*"
Cliente --> CondicionIVA
Cliente --> MedioDeContacto

SolicitudDePoliza --> Cliente
SolicitudDePoliza --> Cobertura
SolicitudDePoliza --> Ubicacion
SolicitudDePoliza --> TipoDeCategoria
SolicitudDePoliza --> ICondicion : "*"

AlertaDeUbicacion --> Poliza
AlertaDeUbicacion --> Ubicacion

GPS --> ReceptorGPS

ReceptorGPS --> Vehiculo

@enduml