@startuml

class FormularioRespondido {
    - persona : Persona
    - formulario : Formulario
    - respuestas : List<Respuesta>
    - puntaje : Long
}

class Formulario {
    - preguntas : List<Pregunta>
}

class Respuesta {
    - pregunta : Pregunta
    - valorTexto : String
    - opcionesChoice : List<Opcion>
}

class Pregunta {
    - titulo : String
    - tipoDePregunta : TipoDePregunta
    - opciones : List<Opcion>
    - esObligatoria : Boolean
}

class Opcion {
    - valorTexto : String
}

enum TipoDePregunta {
    MULTIPLE_CHOICE,
    SINGLE_CHOICE
}

class Ciudadano {
    - nombre : String
    - email : String
    - DNI : String
}

FormularioRespondido --> Ciudadano
FormularioRespondido --> Formulario
FormularioRespondido --> "*" Respuesta

Formulario --> "*" Pregunta

Pregunta --> "*" Opcion

TipoDePregunta --o Pregunta

Respuesta --> Pregunta
Respuesta --> "*" Opcion

@enduml